### ISSUE TITLE
Broken button & Sounds not sharable to Whatsapp

### ISSUE THREAD

**Issue by okranix** [baas-cloud/baas#9]
The 'säuniggel' button does not play a sound when klicking it.

The sounds are not conveniently sharable to whatsapp. It would be awesome if this can be made easier.
Currently I have to download the mp3 file, convert it to .ogg (opus), copy it to my phone and share it to whatsapp.

D Martullo wür jetzt säge: "driimer ju driim du"

**Comment by oxivanisher** [comment]
Ig säge nume https://baas-cloud.github.io/baas/#das_goht_nit ! :D

**Comment by hairmare** [comment]
AFAICT this has been broken for a while and any pull requests to fix it would be highly appreciated.

**Comment by hairmare** [comment]
Thanks @fujexo !
